name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build y correr test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio actual en ubuntu 
        uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Imprimir contenido del directorio
        run: ls -la
        
  generate-apk:
    name: Generar apk
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v1

      - name: Configurar JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generar apk
        run: ./gradlew assembleDebug

      - name: Subir APK
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/build/outputs/apk/debug/app-debug.apk
